export const ADD_PROJECT='ADD_PROJECT';
export const UPDATE_PROJECT='UPDATE_PROJECT';
export const PROJECTS_LOADED='PROJECTS_LOADED'


export const ADD_SKILL='ADD_SKILL'
export const UPDATE_SKILL='UPDATE_SKILL'
export const SKILLS_LOADED='SKILLS_LOADED'