export const skills = [
    {name:"PHP",Rating:3,category:["Backend"]},
    {name:"Javascript / ES6",Rating:5,category:["Front-End"]},
    {name:"MySQL",Rating:3,category:["Database","Backend"]},
    {name:"JQuery",Rating:4,category:["Front-End"]},
    {name:"MongoDB",Rating:3,category:["Backend"]},
    {name:"Node.js",Rating:5,category:["Backend"]},
    {name:"C#",Rating:3,category:["Backend","Front-End"]},
    {name:"ASP.NET",Rating:3,category:["Front-End","Backend"]},
    {name:"Firebase",Rating:4,category:["Backend"]},
    {name:"NoSQL",Rating:3,category:["Backend"]},
    {name:"ReactJS",Rating:5,category:["Front-End"]},
    {name:"Bootstrap",Rating:5,category:["Front-End"]},
    {name:"Electron",Rating:3,category:["Front-End"]},
    {name:"Azure DevOps",Rating:3,category:["DevOps"]},
    {name:"GitHub",Rating:4,category:["Repos"]},
    {name:"Android Native",Rating:2,category:["Mobile"]},
    {name:"React Native CLI",Rating:3,category:["Mobile"]},
    {name:"Expo",Rating:3,category:["Mobile"]},
]